lahmacunradio/arcsi

arcsi/__init__.py, arcsi/api/show.py
Items were using nested schema without the `image_url` being dumped. It is needed to display thumbnails for an archive item of whole show list
=> api -- return image url for items of show

arcsi/api/utils.py
Aims to fix issue #20 
We didn't encode hashmark in our end for filename but Azura does. So when trying to assign audio file to playlist it couldn't find the audio file. It only occured on hashmark so this pull request only fixes that. We can aim to cover other characters too but I didn't have capacity to test them all. 
Tested on dev, fixes the issue
=> fix #20 strip hashmark from filename so it gets assigned to Az playlists

arcsi/__init__.py, arcsi/handler/upload.py, entrypoint.sh
Use app logger but with gunicorn's handlers & log-level so we have unified control over what is logged by Flask & gunicorn both.  
I changed the default log-level in `entrypoint` to info so that log messages sent with debug log-level are not logged by default for production. For dev and local, we can start them w/ debug log-level for work & development purposes.
=> Basic logging setup

arcsi/api/utils.py
We previously managed to control the file's name when user would download. Internally we still used the raw filename's of the assets during upload & archival.
The aim of this PR is to once and for all get rid of the raw filenames and set during upload names that are neutral. 
The schema is very simple. `<show_name>-<ep_name>.<ext>`
=> Issue #36 -- Archive filename set by naming schema on upload

arcsi/api/show.py
Still have not found time for reworking this queriless situation. 
However w/ list comprehension on the list of shows returning from JSON we can eliminate all episodes w/ `play_date` equalling `today()` or `play_date` set to the future
=> Issue #34 -- Quick workaround that filters future episodes 

arcsi/handler/upload.py, config.template.py
Added new possibility to add CDN edge endpoint URL to the config which is then used when downloading files (saving costs and bandwidth). 
Main points:
- For this to work we now set public read ACL on the uploaded files as well as constructing the download path w/ the CDN endpoint URL
- We introduced ARCHIVE_ENDPOINT (perhaps not the best naming idea) as public URL media handler should use
- refactored storage download handler so it uses CDN (should revisit to add some fallback & smarts to this later)
This means once the already stored assets are set to public this can be merged and it can start receiving live requests I think
=> #33 Setup new architecture w/ CDN edge

entrypoint.sh
We have smallish available memory so the upkeep for these workers normally used is bit too high. 
Lowered it and checked that memory is indeed not used by the extra workers and threads
=> More conservative numbers for gunicorn

arcsi/api/utils.py
Previously we had nimble and unstable way to sanitise some incoming or constructed names for audio or image files. I switched to the slugify since we already use it for other purposes. I only changed the underlying logic of the util we use in the API layer so nothing has had to be changed anywhere else. 
I did couple of quick tests in my REPL but not w/ actual test server. Feel free to give it a spin! 
multiple spec. chars 
```
>>> specstring="á/@"
>>> sluggish=slugify(specstring)
>>> strippish=unicodedata.normalize("NFD",specstring).encode("ascii", "ignore").decode("utf-8").lower()
>>> print("{} vs {}".format(sluggish, strippish))
a vs a/@
```
multiple spaces and uppercase
```
>>> bigvalupper="BABA MAMA PAPA ANYA APA"
>>> bigsl=slugify(bigvalupper).replace("-","_")
>>> print(bigsl) …
```
=> Removing spec. chars from all media filenames

entrypoint.sh
#57
Rationale: multiple workers are more expensive than multiple threads. Workers are recommended in case of CPU heavy load (which we don't have) and also if multiple cores are available (which we don't have either).
=> Have a single worker

arcsi/api/utils.py
Previously we already managed to clean up special chars and accents in uniform manner but we failed to address the logic of making sure we are always saving to the binary data to correct extension. What we had was one stop solution for audio assets but we didn't really care of images and it just worked. But with filename normalisation changes it break images and this is an attempt to fix that and provide a concise function that forms filenames correctly based on its input regardless of what extension it is. 
We are currently running both dev and sadly both prod too to not have too many broken images we need to fix later on this branch so if 1 days uploads is any verification than we can verify it works. It also handled cases w/ multiple dots in the filename well.
`some show e19. …
=> Form filenames universally

arcsi/api/item.py, arcsi/api/show.py, arcsi/api/utils.py
**Why?**
It started off as quick-fix for issue #69 but since we had issues with this weak setup we used anyway I started to separate media processing, media archiving, media broadcasting. It is not full rewrite but just step in that direction while the app still works with the same UI and API payload.
**What did I do?**
Introduced `archive()`, `process()` generic functions instead of `process_media()` interface. 
Rewrote parts of add show, edit show, add item, edit item where we deal w/ media handling to use these functions. I made small changes in `form_filename()` (*this is the relevant part to issue #69 fixing that!*) and attempted to improve `broadcast_audio()` too. 
I also formatted the files I touched w/ black. We lost that somewhere but I think it is really-really good and well …
=> Fix #69 and first step to decouple media processing actions from episode handling

config.template.py, docker-compose.yml
This was hardcoded until now and unnecessarily so. 
I've added the `db.env` file as `env_file` to arcsi's docker compose Yml so we can use the values of it via `os.getenv()`
Since the same env values are used for both database setup and connection we should be sure that they will match & work. If there are any issues however we will just fail during web service start so there is no need for extra defensive code, I think. 
Please check it out, I tested locally but you may do it too -- if it is right I hope we can merge it quick. Thanks!
=> Dynamically add db connection values from .env file

arcsi/__init__.py
**Why?**
We have been facing an issue (#8 ) when starting new instances where the app would go and try create roles before the `roles` relation was present in the db. You had to block comment those lines out in `__init__.py` first then undo and run it for the 2nd time. I investigated the root & propose fix here.
**What was the cause?**
```sh
web_1      |   File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 966, in main
web_1      |     cli.main(prog_name="python -m flask" if as_module else None)
web_1      |   File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 586, in main
web_1      |     return super(FlaskGroup, self).main(*args, **kwargs)
web_1      |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 717, in main
web_1      |     rv = …
```
=> Fix #8 -- Fix premature role creation during app startup

.gitattributes, .gitignore
Related: #86
the .gitattributes file helps to evade Windows' auto CRLF line endings nightmare
=> update to help future Windows developers

arcsi/api/item.py
**What was buggy?**
The endpoint wrongly used the value of the existing item's `archive_lahmastore` column to turn `archived` flag `True`. You might have just updated the image of a live show and it would still change like there was audio archived (thanks @tuz666 )
**What did I do?**
I just removed this incorrect statement. No idea why it was even there. I'm sorry for that.
I tested it locally w/ dev: 
Editing w/o audio now doesn't set it to archived
Editing w/ audio still does set it to archived correctly
Please let me know if you have more test cases and do try the branch out, cheers!
=> Fixing bad behaviour of edit show api

arcsi/api/item.py, arcsi/api/utils.py, config.template.py
Currently we only check that file in request sent to API is present (ie. not empty)
I introduced a utility method that takes an allowed extension list (I put this in config for ease of working with it in the future, note: **after merge config update is needed on live instances**) and compares the filename extension to it
To solve the issue presented in #13 I created list for valid audio then list for valid image extensions and added checks to show and episode API's separately.
I think ideally this validation could/should happen right in the client but it's not too expensive and bad to have something defensive like this deep down in the API (we can always remove it later too). So I added it to our backend for now.
Another note. I could have updated the "error message" to reflect that we …
=> Introducing extension validation 

arcsi/api/item.py
**What happened?**
Further highlighting the need to move the form handling and upload logic to a single root the previous hotfix for live episodes only fixed addition and not editing live stuff. This means that editing live episodes to change / add / update img's do not work currently. 
**What did I do?**
Since this is aimed to be another quick bandaid I just added the sound logic from add to edit (w/ minor syntactic update removing braces)
=> Edit live episodes by adding img only

arcsi/api/item.py
**What happened?**
I made an indentation type so if you wanted to edit an episode into a live type one it wasn't possible. Thank you @gammaw for noticing this in #110 
**What did I do?**
Fixed the statement so it is now in it's hopefully correct pos
=> Fix issue to reach path to live ep editing

docker-compose.yml
Please review, we have 7 days to go ;)
Note that the webroot folder needs to be manually created in the certbot container. 
Related issue: https://github.com/mmmnmnm/lahmacun_arcsi/issues/119
=> Add webroot path

nginx/https_arcsi.conf.template
The change attempts to fix the conflict with https://github.com/mmmnmnm/lahmacun_arcsi/blob/0f9bbc8ff36357f3e74a2212b7207bfade60efa7/nginx/https_arcsi.conf.template#L74-L76 
Following @pvj's advise (which was not to comment out the 405 rule because it's good to control what requests are allowed) I allowed the OPTIONS type requests in the rule in question. 
Disclaimer: I haven't tested locally because I thought it was a trivial change. We can test it on our dev server once merged (with the other ongoing tests).
=> Allow OPTIONS request in nginx config

arcsi/api/item.py, arcsi/api/show.py, arcsi/api/utils.py, arcsi/static/component.json, arcsi/static/doc.json, config.template.py
In the previous PR, I forget about Arcsi's view methods & internal pages.
I restored the routes that were used by these features mentioned before.
The Swagger doc is more expressive than ever, it explains the exact use case and responses for every call.
Added the page size parameter for `/item/all_minimal/`
#128
=> Fix/Updated API endpoints and Swagger doc

arcsi/api/item.py, arcsi/api/show.py, arcsi/api/utils.py, arcsi/static/doc.json
In case that we accidentally send a file to the archives that has been already submitted we now change the filename so it can duplicate safely. 
I renamed one utility function `process` to `save_file` as that is way more exact.
The question is what to do on retrieval & display? 
In use-case one, the show host has a late edit (`mixdown-fin-2` etc.) he wants to upload. In that case the file exists so we change file name of the edited episode and upload it. In this case we would need to fetch this new copy
In another case, someone makes a mistake during the upload process and due to that we accidentally tried uploading something so again the name is safely changed but here we want the opposite to happen: retrieve & display the actual episode.
I'm curious what you think or can think of? I'll …
=> Create new file name in case filename already exists

arcsi/api/item.py, arcsi/api/show.py, arcsi/api/utils.py
- In a previous merged commit I accidently removed the archived boolean from ShowDetailsSchema's items field. Sorry for that, I believed that we are getting the items of the given show from the /show/{slug}/archive endpoint
- Moved name duplications checker into utils
=> Quick fix for the legacy API calls

arcsi/api/__init__.py, arcsi/api/data.py, arcsi/api/item.py, arcsi/api/show.py, arcsi/api/user.py, arcsi/static/doc.json, arcsi/templates/base.html, arcsi/templates/data/uploaded_episodes_daily.html, arcsi/templates/data/uploaded_episodes_weekly.html, arcsi/templates/data/view.html, arcsi/view/__init__.py, arcsi/view/data.py
Added 2 new API endpoints which returns the sum of the uploaded items during the last x days/weeks from the given date.
Introduced new statistics related view pages on Arcsi UI, to be able to reach these info without Postman requests.
Updated the Swagger docs according to this.
Also added some constraints on API URL's variables, in order to prevent incorrect API calls (changes in item.py, show.py, user.py).
=> New endpoint for analytics

.github/workflows/main.yml, arcsi/model/user.py, requirements.txt, test/postman/functional_test.postman_collection.json, test/postman/robustness_test.postman_collection.json, test/postman/test.postman_environment.json
I opened this new branch because the [previous](https://github.com/lahmacunradio/arcsi/pull/157) got messed up during a rebase.
The currently used [flask-security](https://flask-security.readthedocs.io/en/3.0.0/) package is no longer supported (latest change is 2,5 years old), [flask-security-too](https://flask-security-too.readthedocs.io/en/stable/) is the maintained up-to-date version of it.
Previously we talked about @gammaw that introducing the authentication made the frontend page is a bit slower.
This new security package offers some performance boost with version [3.1.0](https://github.com/Flask-Middleware/flask-security/blob/master/CHANGES.rst#version-310) and [3.2.0](https://github.com/Flask-Middleware/flask-security/blob/master/CHANGES.rst#version-320), for these uplifts we need …
=> Changing flask-security to flask-security-too

arcsi/api/show.py
In order to be sync with the frontend we had to introduce a workaround in the previously merged PR (#172)
The changed API was already used by the frontend without any `filters` and the expected response was a filtered (without upcoming episodes) `items` field under the returned `show`.
Since the `archived` flag is added to the frontend code (in this PR https://github.com/lahmacunradio/frontend/pull/291) where it is needed, we can remove this workaround which added the `archived` flag in case the request was coming from the frontend
Connecting issues:
- https://github.com/lahmacunradio/frontend/issues/288
- https://github.com/lahmacunradio/frontend/issues/289
=> Remove temporary API workaround

nginx/Dockerfile
In a [previous PR](https://github.com/lahmacunradio/arcsi/pull/176) I wrongly updated the version of nginx.
Although I tested the updated version locally on the prod server it had some issues and couldn't come up, I had to manually overwrite the version to the previous stable one.
=> Revert nginx version update

Dockerfile, infra/tmpreaper.conf
**Why?**
We tend to write to tmp storage any file that is posted to arcsi which may fill the disk before we ever restart the system. Manually checking and deleting files is cumbersome and may result in errors (an open file is forcibly deleted)
**What has changed?**
A proven, old, stable utility for this situation has been added to our image -- please read [the manual for tmpreader](https://manpages.ubuntu.com/manpages/lunar/en/man8/tmpreaper.8.html) for details on how and what it can do
Also added a config file that specifies that files not touched within 21 days should be removed. The default directory where tmpreaper works is `/tmp/` so there is no need to set anything else. 
**How does it work?**
Upon install tmpreaper adds a job to `/etc/cron.daily` which uses the config file at …
=> Using tmpreaper utility to maintain the tmp files

arcsi/api/item.py, arcsi/api/show.py, arcsi/api/tag.py, arcsi/static/component.json, arcsi/static/doc.json, test/postman/functional_test.postman_collection.json
The goal of this PR is to extend the schemas connected to the newly introduced Tags and make them ready for the frontend usage.
Besides the schema extensions, I fixed a little glitch which caused unnecessary whitespaces, updated the Postman tests and Swagger docs.
=> Prepare Tags for frontend usage

.github/workflows/main.yml, arcsi/api/item.py, arcsi/api/show.py, arcsi/view/item.py, arcsi/view/show.py, arcsi/view/tag.py, arcsi/view/user.py, docker-compose.yml, entrypoint.sh, test/postman/functional_test.postman_collection.json, test/postman/robustness_test.postman_collection.json
Massive performance boost for Archon (Arcsi UI) pages.
- I did a refactor for the `view`/`router` endpoints:
- Previously we called the `api`/`arcsi` endpoints inside these endpoints, which as we saw put some additional, not properly handled load on the gunicorn workers
- I refactored these endpoints to call the exact `api`/`arcsi` functions from the code instead of calling the exposed endpoints
- These resulted a significantly faster response for Archon show and episode subpages, and a slightly faster response for the big, 'Shows archive' and 'Items archive' pages.
- I also had to align the flask-security related decorators, for the directly used `api`/`arcsi` endpoints/functions
I had to align the CI tests as well.
Small fix in `entrypoint.sh` for the cron job to properly start when the …
=> Refactor Archon (Arcsi UI) endpoints

.github/workflows/main.yml, arcsi/__init__.py, arcsi/api/item.py, arcsi/api/show.py, arcsi/api/user.py, arcsi/api/utils.py, arcsi/model/role.py, arcsi/templates/base.html, arcsi/templates/item/add.html, arcsi/templates/item/edit.html, arcsi/templates/item/list.html, arcsi/templates/item/view.html, arcsi/templates/show/add.html, arcsi/templates/show/edit.html, arcsi/templates/show/view.html, arcsi/templates/user/view.html, arcsi/view/item.py, arcsi/view/show.py, arcsi/view/user.py, docker-compose.yml, requirements.txt, test/postman/functional_test.postman_collection.json
- Cleaned up authentication annotations
- Separated Admin and Host use cases for Show and Item handling
- Admins have access for each Show and Item by default
- Hosts have access for managed Shows and the connecting Episodes/Items
- Removed not yet implemented features such as User edit and Show/Item delete from the views
- Added CKEdit for basic formatting features on descriptions
- Extended error messages, in case of Episode upload failures, now they are returned in the error response and logged as well
- Removed unnecessary User field from Show add and edit form, now it uses current_user by default
- Adjusted CI tests for the User field related change
- Item and Show edit form uses the stored language by default
- Fixed a bug on Admin's all Users view
- Uplifts for GitHub Actions
=> Archon RBAC, Welcome Show Hosts!
